import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import SectionCard from "../components/shared/SectionCard";
import StatusBadge from "../components/shared/StatusBadge";
import { formatDate } from "../utils/formatDate";
import { closeJobCard as closeJobCardRequest, getJobCard, sendFeedbackEmail } from "../services/jobCardService";

export default function Delivery() {
  const { jobCardId } = useParams();
  const [jobCard, setJobCard] = useState(null);
  const [error, setError] = useState("");
  const [successMessage, setSuccessMessage] = useState("");

  useEffect(() => {
    getJobCard(jobCardId).then(setJobCard);
  }, [jobCardId]);

  if (!jobCard) return <main className="app-shell">Loading closure summary...</main>;

  const closeCurrentJobCard = async () => {
    try {
      const result = await closeJobCardRequest(jobCard.id);
      setJobCard(result.jobCard);
      setError("");
      setSuccessMessage(result.pdfPath || result.gatePassPath
        ? `Job card closed. Job card PDF${result.pdfPath ? " created" : " skipped"} and gate pass${result.gatePassPath ? " created" : " skipped"}; both email flows were scheduled in background.`
        : "Job card closed. Job card PDF and gate pass generation failed gracefully, but the background email flow still ran.");
    } catch (err) {
      setError(err.response?.data?.detail || "Unable to close job card.");
    }
  };

  const triggerFeedback = async () => {
    try {
      await sendFeedbackEmail(jobCard.id);
      setSuccessMessage("Feedback form email scheduled in background for kumudhaaa10@gmail.com.");
      setError("");
    } catch (err) {
      setError(err.response?.data?.detail || "Unable to schedule feedback email.");
    }
  };

  return (
    <main className="app-shell space-y-6">
      <SectionCard title={`Delivery & Closure · ${jobCard.job_card_no}`} subtitle={`${jobCard.customer_name} · ${jobCard.reg_no}`}>
        <div className="grid gap-4 lg:grid-cols-3">
          <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs uppercase tracking-[0.14em] text-slate-500">Status</p><div className="mt-3"><StatusBadge value={jobCard.status} /></div></div>
          <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs uppercase tracking-[0.14em] text-slate-500">Payment</p><div className="mt-3"><StatusBadge value={jobCard.payment_status} /></div></div>
          <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs uppercase tracking-[0.14em] text-slate-500">Estimated Delivery</p><p className="mt-3 text-sm font-semibold text-slate-800">{formatDate(jobCard.estimated_delivery_at, true)}</p></div>
        </div>
        <div className="mt-5 flex flex-wrap gap-3">
          <button type="button" onClick={closeCurrentJobCard} className="rounded-full bg-primary-500 px-5 py-3 text-sm font-semibold text-white">Close Job Card</button>
          <button type="button" onClick={triggerFeedback} className="rounded-full border border-slate-300 px-5 py-3 text-sm font-semibold text-slate-700">Send Feedback Form</button>
          {error ? <p className="text-sm font-medium text-rose-600">{error}</p> : null}
          {successMessage ? <p className="text-sm font-medium text-emerald-700">{successMessage}</p> : null}
        </div>
      </SectionCard>

      <SectionCard title="Notification Log" subtitle="Invoice and reminder events generated by backend workflow">
        <div className="space-y-3">
          {jobCard.notifications.map((item) => (
            <div key={item.id} className="rounded-2xl border border-slate-200 p-4 text-sm text-slate-700">
              <p className="font-semibold text-slate-800">{item.notification_type}</p>
              <p>{item.recipient}</p>
              <p>{formatDate(item.triggered_at, true)}</p>
            </div>
          ))}
        </div>
      </SectionCard>
    </main>
  );
}
